# Generated by Django 4.2.5 on 2023-10-14 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion_de_citas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antecedentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diabetes', models.BooleanField()),
                ('hta', models.BooleanField()),
                ('cardiaco', models.BooleanField()),
                ('operaciones', models.BooleanField()),
                ('otros', models.CharField(max_length=200)),
                ('alergias', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DolorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField()),
                ('area', models.CharField(max_length=100)),
                ('punto_gatillo', models.CharField(max_length=100)),
                ('palpacion', models.BooleanField()),
                ('distribucion', models.CharField(max_length=12)),
                ('ocurrencia', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionCorporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esquema_corporal', models.CharField(max_length=100)),
                ('sensibilidad', models.CharField(max_length=12)),
                ('tipo_sensibilidad', models.CharField(max_length=15)),
                ('nivel_fuerza', models.IntegerField()),
                ('tono_muscular', models.CharField(max_length=15)),
                ('trofismo_muscular', models.CharField(max_length=15)),
                ('rango_articular', models.IntegerField()),
                ('retracciones_musculares', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExamenFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado_funcional', models.CharField(max_length=18)),
                ('actitud_postural', models.CharField(max_length=18)),
                ('reflejos', models.CharField(max_length=12)),
                ('actividades_motoras', models.CharField(max_length=50)),
                ('coordinacion', models.BooleanField()),
                ('orientacion', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Observaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traqueostomia', models.BooleanField()),
                ('upp', models.BooleanField()),
                ('control_esfinter', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Trastornos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vasculares', models.CharField(max_length=100)),
                ('afasia', models.CharField(max_length=15)),
                ('disartria', models.CharField(max_length=15)),
                ('disfagia', models.BooleanField()),
                ('disfonia', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enfermedad', models.CharField(max_length=60)),
                ('tiempo_enfermedad', models.IntegerField()),
                ('diagnostico_medico', models.CharField(max_length=100)),
                ('diagnostico_terapeutico', models.CharField(max_length=100)),
                ('plan_tratamiento', models.CharField(max_length=500)),
                ('antecedentes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='historial_medico.antecedentes')),
                ('dolor_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='historial_medico.dolorinfo')),
                ('evaluacion_corporal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='historial_medico.evaluacioncorporal')),
                ('examen_fisico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='historial_medico.examenfisico')),
                ('observaciones', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='historial_medico.observaciones')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion_de_citas.paciente')),
                ('trastornos', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='historial_medico.trastornos')),
            ],
        ),
    ]
