# Generated by Django 4.2.5 on 2023-10-14 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion_de_citas', '0001_initial'),
        ('historial_medico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historial_medico.evaluacion'),
        ),
        migrations.AddField(
            model_name='cita',
            name='terapista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion_de_citas.terapista'),
        ),
    ]
