# Generated by Django 4.2.5 on 2023-10-14 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion_de_citas', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terapista',
            old_name='estado',
            new_name='activo',
        ),
    ]
